#!/bin/bash

# Author: Tushar

# Variables
BASE="/mnt/c/Users/Lenovo/projects"
DAYS=10
DEPTH=1
RUN=0

# Check if the directory is present or not
if [[ ! -d "$BASE" ]]; then
    echo "Directory not present: $BASE"
    exit 1
fi

# Create archive folder if not present
if [[ ! -d "$BASE/archive" ]]; then
    mkdir "$BASE/archive"
fi

# Find the list of files larger than 20MB
for i in $(find "$BASE" -maxdepth "$DEPTH" -type f -size +20M); do
    if [ "$RUN" -eq 0 ]; then
        echo "[$(date)] Compressing: $i"
        gzip "$i" || exit 1
        mv "${i}.gz" "$BASE/archive/" || exit 1
    fi
done
